updated rmq-build.yaml file

diff --git a/.github/workflows/rmq-build.yaml b/.github/workflows/rmq-build.yaml
--- a/.github/workflows/rmq-build.yaml
+++ b/.github/workflows/rmq-build.yaml
@@ -66,22 +66,29 @@ jobs:
          run: |
               dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.*
               reportgenerator -reports:./RMQApi/RMQApi.Tests/testResults/coverage.cobertura.xml -targetdir:./testResults/coverage -reporttypes:TextSummary
+                                     
+              echo "Checking if Summary.txt exists"
+              if [ ! -f testResults/coverage/Summary.txt ]; then
+                 echo "Summary.txt not found - report generation failed"
+                 exit 1
+              fi
+              echo "Contents of Summary.txt:"
+              cat testResults/coverage/Summary.txt
+
               coverage=$(grep -oP 'Line coverage:\s*\K\d+(\.\d+)?' testResults/coverage/Summary.txt)
-                                            
-              # Debugging step to show the coverage value
-              echo "Coverage extracted: $coverage"
+              echo "Extracted coverage: $coverage"
+
               # Check if coverage is empty
               if [[ -z "$coverage" ]]; then
                  echo "No coverage data found - failing the build."
                  exit 1
               fi
-                                                        
               # Check if coverage is below 85%
               if (( $(echo "$coverage < 85.0" | bc -l) )); then
                  echo "Test coverage is below 85% - failing the build."
                  exit 1
               fi
-              echo "Test coverage is above 85%."   
+              echo "Test coverage is above 85%."
      # Step 10: Build Docker image using the Dockerfile in the root of the repository
        - name: Build Docker image
          run: |
