updated rmq-build.yaml file

diff --git a/.github/workflows/rmq-build.yaml b/.github/workflows/rmq-build.yaml
--- a/.github/workflows/rmq-build.yaml
+++ b/.github/workflows/rmq-build.yaml
@@ -65,9 +65,14 @@ jobs:
               reportgenerator -reports:RMQApi/RMQApi.Tests/testResults/coverage.cobertura.xml -targetdir:testResults/coverage -reporttypes:TextSummary
               coverage=$(cat testResults/coverage/Summary.txt | grep -Po '(?<=Line coverage: )\d+(\.\d+)?')
               echo "Test Coverage: $coverage%"
+              if [[ -z "$coverage" ]]; then
+                echo "No coverage data found - failing the build."
+                exit 1
+              fi
               if (( $(echo "$coverage < 85.0" | bc -l) )); then
-                 echo "Test coverage is below 85% - failing the build."
-                 exit 1   
+                echo "Test coverage is below 85% - failing the build."
+                exit 1
+              fi
          shell: bash            
      # Step 9: Build Docker image using the Dockerfile in the root of the repository
        - name: Build Docker image
